/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import static controller.SQLServerConnection.closeConnection;

import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.JOptionPane;
import javax.swing.JTable;

import controller.ControllerDosen;

public class Dosen extends javax.swing.JInternalFrame {
    ControllerDosen controllerDosen;
   
    public Dosen() {
        initComponents();
        TampilDataDosen();
    }

    private void TampilDataDosen() {
        controllerDosen = new ControllerDosen(this); // ok
        controllerDosen.viewListDosen(); // ok
    }

    public void setTableDosen(JTable tableDosen) {
        this.tableDosen = tableDosen;
    }
    
    public JTable getTableDosen() {
        return this.tableDosen;
    }

    public String gettfNip() {
        return this.tfNip.getText();
    }

    public String gettfNama() {
        return this.tfNama.getText();
    }

    public String gettfTmpLahir() {
        return this.tfTmpLahir.getText();
    }

    public String getspTglLahir() {
        String TglLahir = spTglLahir.getValue().toString();
        String Year = TglLahir.substring(24);
        String Month = TglLahir.substring(4, 7);
        switch (Month) {
            case "Jan" -> Month = "01";
            case "Feb" -> Month = "02";
            case "Mar" -> Month = "03";
            case "Apr" -> Month = "04";
            case "May" -> Month = "04";
            case "Jun" -> Month = "06";
            case "Jul" -> Month = "07";
            case "Aug" -> Month = "08";
            case "Sep" -> Month = "09";
            case "Oct" -> Month = "10";
            case "Nov" -> Month = "11";
            case "Dec" -> Month = "12";
        }
        String Day = TglLahir.substring(8, 10);
        return Year + "-" + Month + "-" + Day;
    }

    public String getcbGender() {
        return cbGender.getItemAt(cbGender.getSelectedIndex());
    }
    
    public String gettfSebagai() {
        return cbSebagai.getItemAt(cbSebagai.getSelectedIndex());
    }

    public String gettfAlamat() {
        return tfAlamat.getText();
    }

    public String gettfKabupatenKota() {
        return tfKabupatenKota.getText();
    }

    public String gettfProvinsi() {
        return tfProvinsi.getText();
    }

    private void EmptyForm() {
        int Year = java.time.LocalDate.now().getYear();
        int Month = java.time.LocalDate.now().getMonthValue();
        int Day = java.time.LocalDate.now().getDayOfMonth();
        Calendar calendar = new GregorianCalendar(Year, Month - 1, Day);
        // ----------------------------------------------------------
        tfNama.setText(null);
        tfTmpLahir.setText(null);
        spTglLahir.setValue(calendar.getTime());
        cbGender.setSelectedIndex(0);
        tfAlamat.setText(null);
        tfKabupatenKota.setText(null);
        tfProvinsi.setText(null);
    }

    private void FillForm(int RecNum) {
        tfNip.setText(tableDosen.getModel().getValueAt(RecNum, 0).toString());
        tfNama.setText(tableDosen.getModel().getValueAt(RecNum, 1).toString());
        tfTmpLahir.setText(tableDosen.getModel().getValueAt(RecNum, 2).toString());
        // ----------------------------------------------------------------------
        String Date = tableDosen.getModel().getValueAt(RecNum, 3).toString();
        int Year = Integer.parseInt(Date.substring(0, 4));
        int Month = Integer.parseInt(Date.substring(5, 7));
        int Day = Integer.parseInt(Date.substring(8, 10));
        Calendar calendar = new GregorianCalendar(Year, Month - 1, Day);
        spTglLahir.setValue(calendar.getTime());
        // ----------------------------------------------------------------------
        cbGender.setSelectedItem(tableDosen.getModel().getValueAt(RecNum, 4).toString());
        tfAlamat.setText(tableDosen.getModel().getValueAt(RecNum, 5).toString());       
        tfKabupatenKota.setText(tableDosen.getModel().getValueAt(RecNum, 6).toString());
        tfProvinsi.setText(tableDosen.getModel().getValueAt(RecNum, 7).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNip = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTmpLahir = new javax.swing.JTextField();
        spTglLahir = new javax.swing.JSpinner();
        cbGender = new javax.swing.JComboBox<>();
        tfKabupatenKota = new javax.swing.JTextField();
        tfProvinsi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tfAlamat = new javax.swing.JTextField();
        cbSebagai = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CRUD Dosen");

        jLabel1.setText("NIP");

        jLabel2.setText("Nama Dosen");

        jLabel3.setText("Tmp. Lahir");

        jLabel4.setText("Tgl. Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Alamat");

        jLabel9.setText("Kabupaten/Kota");

        jLabel10.setText("Provinsi");

        jLabel11.setText("Sebagai");

        tfNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNipKeyReleased(evt);
            }
        });

        spTglLahir.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1731047821088L), null, java.util.Calendar.DAY_OF_MONTH));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tableDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDosenMouseClicked(evt);
            }
        });
        tableDosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableDosenKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableDosen);

        jButton1.setText("Tambah/Koreksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbSebagai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DPA", "Dosen Pengajar" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNip, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spTglLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(tfTmpLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfKabupatenKota, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbSebagai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 58, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbSebagai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKabupatenKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (tfNip.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "NIM is Empty");
        else
            controllerDosen.saveDosen();
        TampilDataDosen();
        EmptyForm();
        tfNip.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tfNip.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "NIM is Empty");
        else
            controllerDosen.saveDosen();
        TampilDataDosen();
        tfNip.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfNipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNipKeyReleased
        int RowCount = tableDosen.getModel().getRowCount();
        for (int RecNum = 0; RecNum < RowCount; RecNum++) {
            if (tfNip.getText().equals(tableDosen.getValueAt(RecNum, 0).toString())) {
                FillForm(RecNum);
                break;
            } else
                EmptyForm();
        }
    }//GEN-LAST:event_tfNipKeyReleased

    private void tableDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDosenMouseClicked
        FillForm(tableDosen.getSelectedRow());
    }//GEN-LAST:event_tableDosenMouseClicked

    private void tableDosenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDosenKeyReleased
        FillForm(tableDosen.getSelectedRow());
    }//GEN-LAST:event_tableDosenKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tfNip.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "NIM is Empty");
        else
             controllerDosen.deleteDosen();
        TampilDataDosen();
        EmptyForm();
        tfNip.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        closeConnection();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbSebagai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spTglLahir;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfKabupatenKota;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNip;
    private javax.swing.JTextField tfProvinsi;
    private javax.swing.JTextField tfTmpLahir;
    // End of variables declaration//GEN-END:variables
}
